sudo: required
# We need the systemd for the kubeadm and it's default from 16.04+
dist: xenial
language: python
python:
- "3.7"
env:
  global:
  - CHANGE_MINIKUBE_NONE_USER=true
  - MINIKUBE_WANTUPDATENOTIFICATION=false
  - MINIKUBE_WANTREPORTERRORPROMPT=false
  - MINIKUBE_HOME=$HOME
  - CHANGE_MINIKUBE_NONE_USER=true
  - KUBECONFIG=$HOME/.kube/config
install:
- pip3 install -r requirements.txt
- pip3 install -r test-requirements.txt
- python3 setup.py develop
before_script:
# K8S
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.2.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
- mkdir -p $HOME/.kube $HOME/.minikube
- touch $KUBECONFIG
- sudo minikube start --vm-driver=none --kubernetes-version=v1.15.0
- "sudo chown -R travis: /home/travis/.minikube/"
# Following is just to demo that the kubernetes cluster works.
- kubectl cluster-info
# Verify kube-addon-manager.
# kube-addon-manager is responsible for managing other kubernetes components, such as kube-dns, dashboard, storage-provisioner..
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl -n kube-system get pods -lcomponent=kube-addon-manager -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for kube-addon-manager to be available"; kubectl get pods --all-namespaces; done
# Wait for kube-dns to be ready.
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl -n kube-system get pods -lk8s-app=kube-dns -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for kube-dns to be available"; kubectl get pods --all-namespaces; done
# - minikube update-context
- kubectl config view
- kubectl create serviceaccount myuser
- kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
- kubectl create clusterrolebinding myuser-cluster-admin --clusterrole=cluster-admin --serviceaccount=default:myuser
# NOMAD
- curl -Lo nomad.tar.gz https://releases.hashicorp.com/nomad/0.7.1/nomad_0.7.1_linux_amd64.zip
- unzip nomad.tar.gz
- chmod +x nomad
- sudo mv nomad /usr/local/bin
- docker run -v /usr/local/bin:/hostbin munnerz/ubuntu-nsenter cp /nsenter /hostbin/nsenter
- nomad agent -dev &

script:
- flake8 aioclustermanager
- SECRET=$(kubectl get serviceaccounts myuser -o jsonpath={@.secrets[0].name})
- export K8S_TOKEN=$(kubectl get secret $SECRET -o jsonpath={@.data.token})
- py.test --cov=aioclustermanager --cov-report=xml aioclustermanager -s
after_success:
- codecov
- rm -rf *.egg-info
